<?xml version="1.0" encoding="utf-8"?><Database Name="EICData" Class="MSSqlEICDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=pumknnutzsql.cdoiaf2cq4xx.us-west-2.rds.amazonaws.com,1433;Initial Catalog=EICData;Persist Security Info=True;User ID=admin" SettingsObjectName="EICSystemTracker.Data.Properties.Settings" SettingsPropertyName="EICDataConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ActivityType" Member="ActivityTypes">
    <Type Name="ActivityType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Association Name="ActivityType_Track_System_Activity" Member="Track_System_Activities" ThisKey="Id" OtherKey="ActivityType" Type="Track_System_Activity" />
    </Type>
  </Table>
  <Table Name="dbo.Track_SystemFaction" Member="Track_SystemFactions">
    <Type Name="Track_SystemFaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="System" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Faction" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Influence" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="CurrentState" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PendingState" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RecoveringState" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ContrllingFaction" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Faction_Track_SystemFaction" Member="EDFaction" ThisKey="Faction" OtherKey="Id" Type="EDFaction" IsForeignKey="true" />
      <Association Name="System_Track_SystemFaction" Member="EDSystem" ThisKey="System" OtherKey="Id" Type="EDSystem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Faction" Member="EDFactions">
    <Type Name="EDFaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChartColor" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="Faction_Track_SystemFaction" Member="Track_SystemFactions" ThisKey="Id" OtherKey="Faction" Type="Track_SystemFaction" />
      <Association Name="Faction_Track_Faction" Member="Track_Factions" ThisKey="Id" OtherKey="Faction" Type="Track_Faction" />
    </Type>
  </Table>
  <Table Name="dbo.System" Member="EDSystems">
    <Type Name="EDSystem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChartColor" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="System_Track_SystemFaction" Member="Track_SystemFactions" ThisKey="Id" OtherKey="System" Type="Track_SystemFaction" />
      <Association Name="System_Track_System" Member="Track_Systems" ThisKey="Id" OtherKey="System" Type="Track_System" />
      <Association Name="System_Track_System_Activity" Member="Track_System_Activities" ThisKey="Id" OtherKey="System" Type="Track_System_Activity" />
    </Type>
  </Table>
  <Table Name="dbo.Track_Faction" Member="Track_Factions">
    <Type Name="Track_Faction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Faction" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Allegiance" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Faction_Track_Faction" Member="EDFaction" ThisKey="Faction" OtherKey="Id" Type="EDFaction" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Track_System" Member="Track_Systems">
    <Type Name="Track_System">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="System" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ControllingFaction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Traffic" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Population" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Government" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="Allegiance" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="Security" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Economy" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="ControllingPower" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ControllingPowerState" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="NeedPermit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="System_Track_System" Member="EDSystem" ThisKey="System" OtherKey="Id" Type="EDSystem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Track_System_Activity" Member="Track_System_Activities">
    <Type Name="Track_System_Activity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActivityType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="System" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumHighMissions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumMedMissions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumLowMissions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreditsClaimed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExploreValueSold" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShipsTaken" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tonnage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BountyEarned" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Cmdr" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="ActivityType_Track_System_Activity" Member="ActivityType1" ThisKey="ActivityType" OtherKey="Id" Type="ActivityType" IsForeignKey="true" />
      <Association Name="System_Track_System_Activity" Member="EDSystem" ThisKey="System" OtherKey="Id" Type="EDSystem" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetLatestSystemTracking" Method="GetLatestSystemTracking">
    <Parameter Name="sysName" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="GetLatestSystemTrackingResult">
      <Column Name="SystemName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SystemChartColor" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="FactionName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FactionChartColor" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Traffic" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Population" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Government" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="Allegiance" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="Security" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Economy" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
      <Column Name="ControllingPower" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ControllingPowerState" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="NeedPermit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Influence" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="CurrentState" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PendingState" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RecoveringState" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>